// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHQiT4UVaq7i239arwg0Gki-y6ktAV90',
    appId: '1:1053621810390:web:626714e190b96d1e1cc577',
    messagingSenderId: '1053621810390',
    projectId: 'rentora-app',
    authDomain: 'rentora-app.firebaseapp.com',
    storageBucket: 'rentora-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2TNlBlnjf-pcll01a9R_5L8YUk5Opqw',
    appId: '1:1053621810390:android:4d702c25b718561d1cc577',
    messagingSenderId: '1053621810390',
    projectId: 'rentora-app',
    storageBucket: 'rentora-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjEgEfgDrzrNEuqTtB-7xuwiqwloxdvo',
    appId: '1:1053621810390:ios:19fff792cf6087921cc577',
    messagingSenderId: '1053621810390',
    projectId: 'rentora-app',
    storageBucket: 'rentora-app.firebasestorage.app',
    iosBundleId: 'com.example.rentoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjEgEfgDrzrNEuqTtB-7xuwiqwloxdvo',
    appId: '1:1053621810390:ios:19fff792cf6087921cc577',
    messagingSenderId: '1053621810390',
    projectId: 'rentora-app',
    storageBucket: 'rentora-app.firebasestorage.app',
    iosBundleId: 'com.example.rentoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHQiT4UVaq7i239arwg0Gki-y6ktAV90',
    appId: '1:1053621810390:web:28173e8ecba3e6421cc577',
    messagingSenderId: '1053621810390',
    projectId: 'rentora-app',
    authDomain: 'rentora-app.firebaseapp.com',
    storageBucket: 'rentora-app.firebasestorage.app',
  );

}